mod.mc_dep_fabric=>=1.20 <=1.20.4
deps.minecraft=1.20.1
mod.mc_targets=1.20 1.20.1

deps.fabric_api=0.92.3+1.20.1
deps.modmenu_version=7.2.2

deps.cloth_version=11.1.118
deps.jade_version=11.10.0+fabric
deps.wthit_version=8.13.2
deps.forge_config_api_port=8.0.1
deps.fast_item_frames=vmfgQQur
deps.puzzles_lib=6dQXvzl5
deps.placeholder_api=2.1.4+1.20.1
deps.architectury=9.2.14